function Dataset_name = loadingDatasets

Dataset_name = {...
    'AgaR',...%
    'AraC',...%
    'ArcA',...%
    'ArgR',...%
    'CpxR',...%
    'CRP',...%
    'CysB',...%
    'CytR',...%
    'DeoR',...%
    'DnaA',...%
    'FadR',...%
    'Fis',...%
    'FlhDC',...%
    'FNR',...%
    'Fur',...%
    'GadE',...
    'GalR',...%
    'GalS',... 
    'GcvA',...%
    'GlpR',...%
    'GntR',...%
    'H-NS',...%
    'IclR',...%
    'IHF',...%
    'IscR',...%
    'LexA',...%
    'Lrp',...%
    'MalT',...%
    'MarA',...%
    'MelR',...%
    'MetJ',...%
    'MetR',...%
    'ModE',...%
    'Nac',...%
    'NagC',...%
    'NanR',...%
    'NarL',...%
    'NarP',...%
    'NtrC',...%
    'OmpR',...%
    'OxyR',...%
    'PhoB',...%
    'PhoP',...%
    'PspF',...%
    'PurR',...%
    'RcsAB',...%
    'Rob',...%
    'SoxS',...%
    'TorR',...%
    'TrpR',...
    'TyrR',...
    'UxuR',...
    };